version: "3.8"
networks:
    traefik:
        external:
            name: traefik
services:
    mongo:
        image: mongo:6
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: tivoli
            MONGO_INITDB_ROOT_PASSWORD: changeme
            MONGO_INITDB_DATABASE: tivolispace
        volumes:
            - ./db:/data/db
    tivolispace:
        build: .
        restart: always
        depends_on:
            - db
        # see all in src/environment.ts
        environment:
            URL: http://127.0.0.1:3000
        
            JWT_SECRET: changeMe!

            STEAM_APP_ID: 2161040
            STEAM_DEV_API_KEY: ""
            STEAM_WEB_API_KEY: ""

            DB_URI: mongodb://tivoli:changeme@mongo:27017/tivolispace
        labels:
            - traefik.enable=true
            - traefik.http.routers.tivolispace.rule=Host("tivoli.space") || Host("www.tivoli.space")
            - traefik.http.routers.tivolispace.entrypoints=websecure
            - traefik.http.routers.tivolispace.service=tivolispace
            - traefik.http.routers.tivolispace.tls=true
            - traefik.http.services.tivolispace.loadbalancer.server.port=3000
            - traefik.docker.network=traefik
        networks:
            - default
            - traefik
