# https://game.ci/docs/github/builder#complete-example

name: Canary build and publish
# on: [push]
on:
    workflow_dispatch:
        # inputs:
        #     version:
        #         type: string
        #         required: true
        #         description: "Semantic version: x.x.x"
jobs:
    build-client:
        name: Build client ${{ github.event.inputs.version }} for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - targetPlatform: StandaloneWindows64
                      itchioChannel: windows
                    - targetPlatform: StandaloneOSX
                      # not doing arm64 for now because of steam audio
                      buildMethod: Tivoli.Editor.MacIntelBuildScript.Build
                      itchioChannel: osx
                    # - targetPlatform: StandaloneLinux64
                    # - targetPlatform: Android
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  # fetch-depth: 0
                  lfs: true

            - name: Fetch cache
              uses: actions/cache@v2
              with:
                  path: client/Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-

            - name: Set version
              run: |
                  echo "version=$(date --utc +%Y.%m%d.%H%M%S)" >> $GITHUB_ENV

            - name: Build client
              uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  projectPath: client/
                  buildName: Tivoli Space
                  targetPlatform: ${{ matrix.targetPlatform }}
                  buildMethod: ${{ matrix.buildMethod }}
                  versioning: Custom
                  version: ${{ env.version }}
                  # version: ${{ github.event.inputs.version }}

            # # permissions are lost when we dont tar.gz it first
            # # https://github.com/actions/upload-artifact/#maintaining-file-permissions-and-case-sensitive-files
            # - name: Tar.gz build
            #   run: |
            #       tar -czf '${{ matrix.targetPlatform }}.tar.gz' 'build/${{ matrix.targetPlatform }}'

            # - name: Upload artifact
            #   uses: actions/upload-artifact@v3
            #   with:
            #       name: Client-${{ matrix.targetPlatform }}-${{ github.event.inputs.version }}
            #       path: ${{ matrix.targetPlatform }}.tar.gz

            - name: Upload to itch.io
              uses: robpc/itchio-upload-action@v1
              with:
                  path: build/${{ matrix.targetPlatform }}
                  project: makifoxgirl/tivolispace
                  channel: ${{ matrix.itchioChannel }}
                  api-key: ${{ secrets.BUTLER_CREDENTIALS }}
                  version: ${{ env.version }}
                  # version: ${{ github.event.inputs.version }}
