# https://game.ci/docs/github/builder#complete-example
name: Manual build from main
# on: [push]
on:
    workflow_dispatch: {}
jobs:
    build:
        name: Build for ${{ matrix.targetPlatform }}
        # runs-on: ubuntu-latest
        runs-on: self-hosted
        strategy:
            fail-fast: false
            matrix:
                include:
                    - targetPlatform: StandaloneWindows64
                      platformName: Windows
                    # intel 64-bit, not doing arm64 for now because of steam audio
                    - targetPlatform: StandaloneOSX
                      platformName: macOS (Universal)
                    # - targetPlatform: StandaloneLinux64
                    #   platformName: Linux
                    # - targetPlatform: Android
                    #   platformName: Quest
        env:
            outputFilename: Tivoli Space dev - ${{ matrix.platformName }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  # fetch-depth: 0
                  lfs: true

            - name: Fetch cache
              uses: actions/cache@v2
              with:
                  path: client/Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-

            - name: Build client
              uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  projectPath: client/
                  buildName: Tivoli Space
                  targetPlatform: ${{ matrix.targetPlatform }}
                  allowDirtyBuild: true

            - name: Make .tar.gz for macOS
              if: ${{ matrix.targetPlatform == 'StandaloneOSX' }}
              run: |
                  cd build/StandaloneOSX
                  tar -czf '${{ env.outputFilename }}.tar.gz' *.app

            - name: Upload artifact for macOS
              if: ${{ matrix.targetPlatform == 'StandaloneOSX' }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.outputFilename }}
                  path: build/StandaloneOSX/${{ env.outputFilename }}.tar.gz

            - name: Upload artifact
              if: ${{ matrix.targetPlatform != 'StandaloneOSX' }}
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ env.outputFilename }}
                  path: build/${{ matrix.targetPlatform }}
